

services:
  api:
    build:
      dockerfile: Dockerfile
    container_name: nest_api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - redis
      - minio
    networks:
      - backend
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
      command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data:
  minio_data: