services:
  db:
    image: postgres:15-alpine
    container_name: zahro_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zahro_dental
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  api:
    image: 10449/zahrodent_backend:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_api
    restart: always
    ports:
      - "7878:7878"
    environment:
      - PORT=7878
      # Docker tarmog'ida db xostiga ulanish uchun (localhost emas)
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/zahro_dental?schema=public
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:

volumes:
  pgdata:
